### ISSUE TITLE
Backfill crash

### ISSUE THREAD

**Issue by kerzhner** [mistercrunch/airflow#228]
We are seeing a crash when running `airflow backfill` using Airflow version 0.6.0. The backfill command does **not** crash with the `-l` flag. Have you guys seen this issue before? The stack trace is:

```
Traceback (most recent call last):
  File "/home/ubuntu/etl/env/bin/airflow", line 10, in <module>
    args.func(args)
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/airflow/bin/cli.py", line 92, in run
    DagPickle).filter(DagPickle.id == args.pickle).first()
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2444, in first
    ret = list(self[0:1])
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2280, in __getitem__
    return list(res)
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 84, in instances
    util.raise_from_cause(err)
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 69, in instances
    rows = [proc(row) for row in fetch]
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 426, in _instance
    loaded_instance, populate_existing, populators)
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 484, in _populate_full
    dict_[key] = getter(row)
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1261, in process
    return loads(value)
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/dill/dill.py", line 209, in loads
    return load(file)
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/dill/dill.py", line 199, in load
    obj = pik.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/dill/dill.py", line 278, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named sensors
[2015-05-21 16:53:52,125: ERROR/Worker-11] 1
[2015-05-21 16:53:52,138: ERROR/MainProcess] Task airflow.executors.celery_executor.execute_command[6a030a02-0023-4585-88ec-d9bcd1c40a18] raised unexpected: Exception('Celery command failed',)
Traceback (most recent call last):
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/etl/env/local/lib/python2.7/site-packages/airflow/executors/celery_executor.py", line 38, in execute_command
    raise Exception('Celery command failed')
```

**Comment by mistercrunch** [comment]
Looks like a problem while unpickling, as if the context or environment in the subprocess can't access the sensors module...

Somewhat related: I think I'll move to the default behavior to be a local backfill, and for remote backfill to not pickle by default unless specified.

**Comment by mistercrunch** [comment]
Oh btw you might be interested in the new features I just pushed around Pools  & Queues

**Comment by mistercrunch** [comment]
@kerzhner, is this still a problem @1.0.1?

**Comment by kerzhner** [comment]
@mistercrunch We have been using local backfills exclusively. We aren't really effected by this crash. Let's close the issue for now.

Pools and Queues look awesome!
